spring.application.name=propertymart
spring.datasource.url=jdbc:mysql://localhost:3306/propertymart
spring.datasource.username=root
spring.datasource.password=rahul@2004


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
